spring:
  profiles:
    include:
      - code
      - swagger
    active: development
  datasource:
    personnel:
      url: jdbc:mysql://10.182.34.185:3306/test_database?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 12345aA)
    vender:
      url: jdbc:mysql://10.182.10.136:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 12345aA)



debug: true

server:
  port: 80


# 和jsf有关的服务配置在这里，方便测试预发线上的不同环境配置和按照项目来修改
jsf:
  jd:
    service:
      a:
        alias: aalias
        timeOut: 5000
      b:
        alias: balias
        timeOut: 5000
mybatis:
  type-aliases-package: com.gateway.project.domain




